# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd45779432dbfcf246e4cbe0024a1477564e9b87a7b9017113463c6d8aafeed3a2e2bb3b6b397a1d7d69358c9a94441841bcd3d2d990ebcdbba8f5e702264728

test:
  secret_key_base: b017d278568169863d0a208048ccafa1cc1986ffb4994b83d952d8825b3c48b4b0532656c9063d6da0bc0e5245ef26b696ee8295e9e94e9ca9acd92314211fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
